### ISSUE TITLE
unexpected behavior of omitempty

### ISSUE THREAD

**Issue by djgilcrease** [go-yaml/yaml#113]
So omitempty behaves in an unexpected way (to me at least) on int and bool values. 0 and false are not empty values for these types so I would expect them to Marshal as set

``` go
type T struct {
    A int `yaml:"a, omitempty"`
    B int
    C bool `yaml:"c, omitempty"`
    D bool
}
b, _ := yaml.Marshal(&T{A: 0, B: 0, C: false, D: false})
fmt.Printf("%s\n", b) 
```

I would expect to output

```
a: 0
b: 0
c: false
d: false
```

But what I get instead is 

```
b: 0
d: false
```

**Comment by packrat386** [comment]
This is consistent with the function of omitempty in standard library packages such as `encoding/json`

```
package main

import "fmt"
import "encoding/json"

type Test struct {
    A int `json:"a,omitempty"`
    B int
    C bool `json:"c,omitempty"`
    D bool
}

func main() {
    b, _ := json.Marshal(&Test{A: 0, B: 0, C: false, D: false})

    fmt.Println(string(b))
}
```

gives output `{"B":0,"D":false}` (http://play.golang.org/p/_3gwocwQFJ)

Unfortunately, `0` and `false` have to be treated as the empty values for `int` and `bool` since otherwise there would be no value by which they could be considered empty. If you need to have those types exported conditionally, I would suggest using `*int` and `*bool` since then the only empty value is for the pointer to be `nil`

**Comment by samsalisbury** [comment]
I think this issue should be closed now, cc @niemeyer

**Comment by mihai-chiorean** [comment]
I have a case where 

```
field []string `json:",omitempty"`
```

translates to

```
field: []
```

instead of being ignored

**Comment by packrat386** [comment]
Do you have the `json` tag? Because you need the `yaml` tag for this library to work.

**Comment by niemeyer** [comment]
As was pointed out here, omitempty behaves in a way consistent with conventional practices elsewhere.
