### ISSUE TITLE
Double semicolon in yaml causes unmarshal error

### ISSUE THREAD

**Issue by xorl** [go-yaml/yaml#140]
```
ops_params:
  subservices:
- vmhost::test
```

The final line 3 causes 
line 3: cannot unmarshal !!seq into string.

Is this caused by a bug in unmarshal or me map[string]string type definition.

**Comment by niemeyer** [comment]
This yaml is broken as you have both a map and a sequence at the same level. But the actual code probably has that last line indented further so it's correct, since the error message you're getting says you're trying to unmarshal that sequence (only a single one there) into a string. That's the error.
