### ISSUE TITLE
Improve review & merge time

### ISSUE THREAD

**Issue by jvehent** [go-yaml/yaml#234]
This is an important library for a lot of Go programs, and I think a lot of us wants to help improve it as best we can, but the pull requests seem to sit in the queue for a very long time, forcing us to maintain local forks.

Are the current maintainers open to the idea of adding more maintainers to this repository, and if so, who would these new maintainers be?

**Comment by niemeyer** [comment]
Yes, I realize the queue is far from ideal right now. I have it on my "urgent" queue, yet keep pushing it back in favor of more urgent things. I'll try to work through some of the most critical items this week still.

About more maintainers, that's always welcome obviously. The problem is precisely the question you ask: finding good long term maintainers.

**Comment by jvehent** [comment]
I am guilty of the same issue and reviews tend to sit in my queue for far too long, so no stone is being thrown here.

A solution I found satisfying is protecting sensitive branches to only allow admins to merge, and let contributors review and manage other branches. That doesn't solve the fact that people need to step up, but I believe that making it easier for co-maintainers to participate is a good place to start. It worked for me on a couple projects.
