### ISSUE TITLE
UnmarshalYAML is not called on null values

### ISSUE THREAD

**Issue by mattdee123** [go-yaml/yaml#276]
If I try to unmarshal a `null` into a type with a custom unmarshaller, that function is not called.  This makes it impossible to choose how null is treated in my objects.

Happy to propose a PR, but wanted to make sure this was something that was wanted.

**Comment by niemeyer** [comment]
An empty definition [is one of the representations of yaml's null](http://www.yaml.org/type/null.html).

We don't call the marshaler because if that was a pointer it would be attempting to unmarshal into a nil value. This is indeed a special case, but intentionally, in the sense that nil is a special case.
