### ISSUE TITLE
Support map with custom order

### ISSUE THREAD

**Issue by niemeyer** [go-yaml/yaml#30]
The proper way to support this would be with something like:

```
type MapSlice []MapItem

type MapItem struct {
        Key, Value interface{}
}
```

and then implement first-class marshalling and unmarshalling of maps onto it.

Feature requested via the pull request #27.

**Comment by mattes** [comment]
I think this approach wins! (but requires substantial amount of code changes, I guess).

**Comment by termie** [comment]
some other things on this subject: 

http://pyyaml.org/ticket/29
http://stackoverflow.com/questions/5956473/preserve-key-order-loading-yaml-from-a-file-in-ruby

thanks for looking into it, i feel that human readable formats deserve some ordering expectations even if @ingydotnet never intended them to :p

**Comment by ingydotnet** [comment]
@termie, My YAML implementations always order by default! :P

My feeling is that key order should be thrown away as late as possible in the Load process, and added (via sort or marshalling code) during the Dump process, when it is known that the data is not already key order ready.

So YNY (yaml→native→yaml) roundtripping preserves key order in languages that preserve hash key order, and is predictable in languages that don't.

The long term solution is to process YAML documents according to a "schema" specification (document) that includes a preferred sort order for each type.

fwiw, The verbiage in the YAML spec about key ordering was more influenced by Clark and Oren. I think the concept (and other details like it) need to be revisited.

My basic stance is this:
1. All YAML processing happens according to a **Schema**.
2. In 2014 this Schema idea is conceptual. It _could_ be encoded as a (possibly more than one) YAML Schema format. It could be encoded in code. It could be encoded as configuration.
3. Currently/normally, the Schema for a YAML document is effectively the code in the implementation/processor that is processing it (and the config options used).
4. The default Schema should be close to the implicit JSON Schema.
5. Key order and other details should be able to have their effects and desires encoded into a Schema.

BTW, Does JSON make any assertions on key order?

**Comment by termie** [comment]
@ingydotnet thanks for the response :) re: JSON, Javascript objects preserve order (for whatever reason) despite not really claiming that they need to so everybody who used JSON from javascript came to expect that, the python implementations of json use OrderedDict-like objects to hold them and I suspect the other languages do as well despite the spec saying that they are unordered.

I agree the "real" solution is a schema with preferred order, though in my specific example my use case for ordered results is people defining env variables that might reference other env variables defined before so the schema solution would have to be a list of pairs in a world where map/hash/object order is being randomized

**Comment by niemeyer** [comment]
The go-yaml package does sort by default when marshaling as well, and has always done so. I have changed the summary to clarify that the feature I was considering is a different one.

This also makes me wonder about what was being originally requested. Pull request #27 implies that the ordering is random, which is not true. So maybe there's nothing to be done here.

Regarding JSON-the-spec, no it [does not](http://json.org) assert key ordering either:

> An object is an unordered set of name/value pairs.

**Comment by niemeyer** [comment]
@termie Most people that talk about JSON are referring to [the specification](http://json.org), not general JavaScript objects.

**Comment by termie** [comment]
@niemeyer I think we may be talking about different things (and I also pointed out the difference between the spec and javascript and said the same thing as you so I don't know whether you missed that and are arguing about something I didn't say).

Anyway, the point for me is that given a yaml file with a map where (arbitrary) keys were entered in a particular order, I would like to be able to, in any way, find out the order that those keys were represented in the yaml file, whether this means a separate index, additional metadata or a different parser hint I am fine with it, hell i'd even be willing to listen for parse events (a la SAX back in the day). If this is possible now I'd be happy to use it, in my investigations I couldn't find a way to get it from go-yaml but I may have missed something.

**Comment by niemeyer** [comment]
@termie Sorry, I was just clarifying the question, which was about JSON rather than JavaScript, but we disagree on a few different fronts. For example, I don't think people expect ordering out of JSON in general, and the absolute majority of applications couldn't care less. Python also reflects that and does not respect the ordering by default either:

```
>>> import json
>>> json.dumps(json.loads('{"b": 2, "a": 1}'))
'{"a": 1, "b": 2}'
```

With all that said, I would still like to make the Go yaml package work for you, but I don't think I really understand the problem I'm trying to solve. In what way is the current logic breaking your application?

**Comment by termie** [comment]
@niemeyer a solution like python's would work fine for me:

(from: https://docs.python.org/2/library/json.html specifically the json.load method)

---snip---

object_pairs_hook is an optional function that will be called with the result of any object literal decoded with an ordered list of pairs. The return value of object_pairs_hook will be used instead of the dict. This feature can be used to implement custom decoders that rely on the order that the key and value pairs are decoded (for example, collections.OrderedDict() will remember the order of insertion). If object_hook is also defined, the object_pairs_hook takes priority.

---end snip---

The specific thing I am trying to solve is:

---snip---
in my specific example my use case for ordered results is people defining env variables that might reference other env variables defined before
---endsnip---

take for example:

{{{
  actions:
    - setup_home:
         USERNAME: %server_variable_username%
         NEWHOME: /home/$USERNAME
         WEBDIR: $NEWHOME/www
}}}

If we wanted to execute those in a shell as export USERNAME=termie, etc the order would matter.

Now, there are clearly a variety of workarounds if I were allowed to change the format the users input or get them to expand all their variables themselves, but as I can't the ideal situation for me would be to have any information about which order those keys were specified so that I can add them to the environment in the correct order and preserve their expectations.

**Comment by niemeyer** [comment]
Okay, thanks for the example. It makes the issue clear. The application internally depends on the order of the keys based on attributed semantics.

Support for this is coming via `yaml.MapSlice` as described, then.

**Comment by ingydotnet** [comment]
A couple minor points:

@termie : The YAML format is intended to to be processed via streaming. `libyaml` is a streaming parser. The Go yaml implementation seems to be a port of it. Cannot Go bind to C libraries? Anyway, SAX style processing is encouraged. It's always sad to me how high YAML aimed to be suitable for, and it has become mostly a config file format (a use case we thought it wasn't the best for :-).

@niemeyer: I for one expect key order preservation from JS and more recent Ruby. I'll often shell out to them for yaml/json processing when I care about key order, because I know they do it. (I've only ever seen one JS implementation that didn't preserve key order. (rhino or spidermonkey or some other dead server-side implementation).

**Comment by niemeyer** [comment]
@ingydotnet The JSON spec says it's unordered, and thankfully the vast majority of applications follow suit. I find it quite poor style to depend on orderings for maps that are meant to be used as a key/value mechanism, and have practical experience with multiple bugs and general confusion generated by using them in that fashion in the only application I have seen depending on them for certain things (MongoDB).

That said, this is the go-yaml package, and I'll support the optional use of ordered values to allow people to preserve their logic working and interact with external content.

**Comment by ingydotnet** [comment]
@niemeyer It makes sense for JSON to not guarantee order, since many languages are incapable of doing so (without a lot of extra work). I just call out to Node.js to say turn YAML to JSON without botching key order, since I know that Node works that way.

So I was wondering why you ported libyaml instead of linking to it?

**Comment by niemeyer** [comment]
@ingydotnet Out of curiosity, what was the use case you considered YAML best for?

**Comment by niemeyer** [comment]
@ingydotnet Several reasons for porting it:
- It plays much better with Go concurrency (no C stack, no thread takeover, etc)
- It becomes memory-safe (no corruption, no buffer overflows, etc) 
- It makes better use of the memory management capabilities of Go
- It runs faster since there's a cost associated with bridging with C
- It becomes trivial to cross-compile into other OSes
- It compiles much faster, although that's a minor convenience in this case
- etc

**Comment by ingydotnet** [comment]
@niemeyer, I personally think that YAML does really well in places where humans need to read data, and also write data (though to a lesser degree). YAML is also a full serialization language with a complete type system, references (including circular) and supports any node as a mapping key. Like:

```
{{a: key}:{a, set, of, values}}
```

(That's valid YAML, though I suspect very few people would guess correctly what it loads as.)

YAML was designed to work well for non-terminating message streaming and the like. And of course the main goal was cross language data sharing. This was a big goal back in 2001 when we started out, since JSON was not to arrive on the scene until years later. It was a completely huge coincidence that JSON turned out to be a subset of YAML!

re config: We thought it might be too finicky for config files, since tabs aren't allowed and indentation changes meaning. ie, Usage by non-programmers. I think it's great that it gets used for config, but I'd like to see it used for more intense cross-language data purposes. Maybe it's not ready yet.

BTW, I just wrote my first Go code yesterday. :)

**Comment by niemeyer** [comment]
@ingydotnet Oh, welcome to the team then. :-) And thanks for the background.

I suspect lack of more suitable options is one of the reasons why YAML became so popular as a configuration format. There's still no other good human-oriented format that can represent nesting of the common set of types and other related needs (text line blocks, etc) in a pleasant way. On the other hand, I wish it was slightly more strict in a few places.

Regarding being a superset of JSON, I don't find it so much of a coincidence to be honest. The JSON spec itself is pretty strict, the ECMA standard behind it is pre-2000 and was already popular at the time, and the general syntax style behind it is ancient. On the other side, YAML is very accepting (with 22 ways to say true or false, it's hard to get wrong ;-).

That's probably one of the reasons that kept its use purely as a cross-language conduit low, actually. I would also look for something much simpler and more strict for that, while I can pay a higher price to keep another human happy when reading or writing content.

**Comment by ingydotnet** [comment]
@niemeyer That's the weird thing. JS/ECMA had nothing to do with the YAML "flow" syntax choices. Python (via Clark Evans) was the main influence for that. And it was close enough to Perl, another big influencer. JS wasn't considered. In fact it only got a decent implementation in the past few years. Also I can't even begin to tell you the number of syntax permutations we put on the table. So it really was a pleasant coincidence. There were only a handful of edge cases where JSON was not a strict subset of YAML 1.1, so we "fixed" that for YAML 1.2. :)

If you do IRC, join #yaml on freenode. I'd like to converse about the implicit types. Too much detail to get into here.

**Comment by niemeyer** [comment]
@ingydotnet Ah, certainly, will join you there.

**Comment by niemeyer** [comment]
This feature was implemented. Details in the announcement for yaml.v2:

http://blog.labix.org/2014/09/22/announcing-yaml-v2-for-go

**Comment by marco-m-pix4d** [comment]
For people coming here and wondering about MapSlice for gopkg.in/yaml.v3, see #698.
