### ISSUE TITLE
Empty document "---" should not reset input object

### ISSUE THREAD

**Issue by logrusorgru** [go-yaml/yaml#395]
So, `yaml.Unmarshal([]byte("---"), &out)` reset the out, including `yaml:"-"` fields and including lower case fields. And no way to catch it.

For example
```go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"runtime"

	"gopkg.in/yaml.v2"
)

type Target struct {
	OS   string
	Arch string
}

func (t *Target) SetDefault() {
	t.OS = runtime.GOOS
	t.Arch = runtime.GOARCH
}

func (t *Target) UnmarshalYAML(
	unmarshalFunc func(interface{}) error,
) (
	err error,
) {
	// https://play.golang.org/p/PFA0BzK0S6c
	type target Target
	var temp = target(*t)
	if err = unmarshalFunc(&temp); err != nil {
		return
	}
	if temp.OS != "" {
		t.OS = temp.OS
	}
	if temp.Arch != "" {
		t.Arch = temp.Arch
	}
	return
}

type Content struct {
	Target Target
	Hidden bool `yaml:"-" json:"-"`
	hidden bool
}

func (c *Content) SetDefault() {
	c.Target.SetDefault()
	c.Hidden = true
	c.hidden = true
}

func (c *Content) UnmarshalYAML(
	unmarshalFunc func(interface{}) error,
) (
	err error,
) {
	type content Content
	var temp = content(*c)
	if err = unmarshalFunc(&temp); err != nil {
		return
	}
	if temp == (content{}) {
		return // just a blank content structure
	}
	(*c) = Content(temp)
	return
}

type Input struct {
	Yaml string
	Json string
}

func main() {
	var (
		c   Content
		err error
	)

	for _, in := range []Input{
		{
			``,
			`{}`, // blank string is not valid for the encoding/json
		},
		{
			`---`,
			`{}`,
		},
		{
			`---
required: yes`,
			`{"required":true}`,
		},
		{
			`---
target: {}`,
			`{"target":{}}`,
		},
		{
			`---
target:
  os: plan9
  arch: mips32le`,
			`{"target":{"os":"plan9","arch":"mips32le"}}`,
		},
	} {
		fmt.Println("----")
		fmt.Println("YAML:", in.Yaml)
		fmt.Println("JSON:", in.Json)

		c.SetDefault()
		fmt.Println("populated:   ", c)

		// yaml
		if err = yaml.Unmarshal([]byte(in.Yaml), &c); err != nil {
			log.Fatal(err)
		}
		fmt.Println("yaml decoded:", c)

		c.SetDefault()

		// json
		if err = json.Unmarshal([]byte(in.Json), &c); err != nil {
			log.Fatal(err)
		}
		fmt.Println("json decoded:", c)
	}

}
```
Output will be (note: only the second case has meaning)
```
----
YAML: 
JSON: {}
populated:    {{linux amd64} true true}
yaml decoded: {{linux amd64} true true}
json decoded: {{linux amd64} true true}
----
YAML: ---
JSON: {}
populated:    {{linux amd64} true true}
yaml decoded: {{ } false false}
json decoded: {{linux amd64} true true}
----
YAML: ---
required: yes
JSON: {"required":true}
populated:    {{linux amd64} true true}
yaml decoded: {{linux amd64} true true}
json decoded: {{linux amd64} true true}
----
YAML: ---
target: {}
JSON: {"target":{}}
populated:    {{linux amd64} true true}
yaml decoded: {{linux amd64} true true}
json decoded: {{linux amd64} true true}
----
YAML: ---
target:
  os: plan9
  arch: mips32le
JSON: {"target":{"os":"plan9","arch":"mips32le"}}
populated:    {{linux amd64} true true}
yaml decoded: {{plan9 mips32le} true true}
json decoded: {{plan9 mips32le} true true}
```
The `UnmarshalYAML` methods don't make sense.

**Comment by logrusorgru** [comment]
I think tat it's a bug.

**Comment by niemeyer** [comment]
The yaml package has always had this behavior, whether it's an empty or a non-empty object. We can discuss adding options to have a different behavior, but the current behavior is by design and cannot change without breaking current users.

**Comment by logrusorgru** [comment]
> We can not ..blah... Breaking current users ...blah...

Every bug. Every feature. Every issue. Every PR. Every every.

Why the "current users", if they are caring about compatibility at least a little, Why they are keep using github master?

There is
- vendor/
- vgo
- dep
- gopkg.in

Does the current users exist in reality? Are they skoolboys? Are they from a boarding school for the retarded?

And the main question: who of them really want to overwrite object with zero-object (including `yaml:"-"` and lower case fields) while input is "---"? So useful feature isn't it?

Why don't you just say that this project is abandoned? And nothing will be changed.

**Comment by logrusorgru** [comment]
There would be no problem if the UnmarshalYAML was called during the reset.
And I really can not imagine a case, where it's can break anything.

**Comment by niemeyer** [comment]
We cannot have a conversation unless it's respectful.

**Comment by logrusorgru** [comment]
Contributors spent their time and mind power. As I understand respect is "I'm the main one here, hey y'all, you can wait forever, I don't care, I found a good excuse.". Ok. Good luck.

Anyway, I can't wait forever to resolve an elementary issue. Thus, we can't have a conversation, because it's just a bog. Just a bog. Nothing more.

**Comment by purpleidea** [comment]
@niemeyer I don't know the reporter, but AIUI this is a very serious bug. Discuss with me instead. Here's why:

If you parse a file and want some sensible defaults, you use a method such as described here: https://github.com/go-yaml/yaml/issues/165

*However*, if the yaml file is empty or even a `---` then it resets the defaults to zero values!!

As a result, it's not possible to have defaults in all cases. It wouldn't be the end of the world if there was only one possibility that did this, we could detect with simple string matching, but there are infinite.

1)
```
--- # some comment here
```

2)
```
# this is an empty yaml file with a big comment
```
etc...

The only workaround is to require a minimum of one field named "fake" or something, but that's just stupid.

Can you admit this is a bug and patch it? There's no compatibility promise that is logical about this behaviour. And it's blocking my code. If you have a better idea, please let me know. Thanks

**Comment by purpleidea** [comment]
As an aside, there's one other workaround which I just tested and seems to work so far:

Step 1)
Add a `bug395 bool` field to your struct. Set it to `true` wherever you set your defaults.

Step 2)
After running the parser, if it's not `true`, then assume everything borked, and just return a new struct with all the defaults instead.

Step 3) 
Laugh hilariously at the world. Don't profit.

**Comment by awfm9** [comment]
@niemeyer this is cleary a bug and should not be intended behaviour.

1) The YAML library should not affect any fields that have `yaml:"-"` or are lower case, ever.
2) The YAML library should not unmarshal anything that is not part of the YAML file. That's like creating values out of the void.

No other decoding library does this, and for good reason.

If you want to overwrite a struct with values from a certain format, you can set the fields and then unmarshal. If you want to have everything at zero value, you can simply initialize an empty sturt and then unmarshal. You can get your cake and eat it, too, with the proper approach.

Nobody, and I mean *nobody*, will rely on the behaviour that a unmarshaler should first reset the struct to all zero values, because it just doesn't make sense and is completely counter-intuitive.

I will fork this library and fix this bug, as we need proper unmarshaling behaviour in our project.

**Comment by awfm9** [comment]
See also: http://ghodss.com/2014/the-right-way-to-handle-yaml-in-golang/

```
The go-yaml library intercepts the null and doesn't even bother to call UnmarshalYAML - it just creates a zeroed object itself and assigns it to DOB. This is not only not the behavior we want, but it is inconsistent with how the JSON library works, requiring you to handle subtly different flows and results.
```

Your library is, unfortunately, extremely inconsistent, as is your decision-making.

**Comment by niemeyer** [comment]
> @niemeyer this is cleary a bug and should not be intended behaviour.

I will get it fixed for v3, which is about to be announced. The point was that we couldn't change the behavior without breaking people. It doesn't matter at all what you think people should do or not. Backwards compatibility is not about your opinion.

> Your library is, unfortunately, extremely inconsistent, as is your decision-making.

Your ability to interact with other people is subpar, Max.

**Comment by awfm9** [comment]
I apologize for the rough tone. Indeed, I should not have voiced my frustration like that. I am sorry.

I spent a lot of time reading through issues on this repository. The library frequently breaks reasonable expectations Go developers have for a marshaler/unmarshaler. This leads to frustrating experiences when the behaviour deviates from what is generally the case for other comparable libraries.

This is illustrated nicely by the amount of wrappers that were written around the YAML library to correct such behaviour. People want to use your library, because it is well-written, but some inconsistencies make it unusable for a lot of them.

In this case, for instance, your reasons for not changing the behaviour have already been addressed multiple times, by multiple users, in multiple issues:

1) There is no one who would reasonably rely on the library initializing everything to zero values before unmarshaling, as everyone who would want such behaviour would just pass a new struct.

2) Everyone who has such strong requirements on not breaking things relies on vendoring specific versions of the library and would thus also not have been broken.

3) The fact that it touches `yaml:"-"` and unexported fields is even more dangerous and wasn't addressed at all. Which developer would reasonably expect that?

> I will get it fixed for v3, which is about to be announced. The point was that we couldn't change the behavior without breaking people. It doesn't matter at all what you think people should do or not. Backwards compatibility is not about your opinion.

It seems like you agree yourself that it is broken behaviour, otherwise you wouldn't fix it in v3. When something is a bug, you don't leave it in a library to stay backwards-compatible. You fix it.

**Comment by niemeyer** [comment]
> It seems like you agree yourself that it is broken behaviour, otherwise you wouldn't fix it in v3.
> When something is a bug, you don't leave it in a library to stay backwards-compatible. You fix it.

I'd rather have you upset because you had to wait until v3 for a change in behavior, than having production code broken because we agree that handling things in a different way would be nice. We don't have to agree, but that's the core idea behind API stability and at least under my watch we'll try to respect it.

**Comment by awfm9** [comment]
If I follow your logic, we should never fix bugs relating to undefined behaviour, because it could break programs that rely on the undefined behaviour. I would posit that the correct way to handle people relying on undefined behaviour is to force them not to rely on it, the way Go did when they started forcing random map iteration order.

You can't equate undefined behaviour stability with API stability; it's just a wrong underlying assumption imo.

**Comment by niemeyer** [comment]
That's a bad analogy, as in Go map ordering was already explicitly stated as undefined, and the order was already unpredictable. Here, the behavior is defined, stable, and is not accidental. I might provide history and rationale for why it behaves that way, and it's not the only package to behave that way either, but given where we stand it's not productive to go there now.

Just the fact that typical code can grossly misbehave is enough: if a variable is defined outside a loop, and in the loop there are multiple decodings, the decoded value will have left over content from the previous iterations.

So this is a behavior change, and can break real code, in production, unexpectedly. Good practice says don't do that to a stable library that a lot of people depend on.

Thanks for the report, though. It was useful as a reminder to look into this. Have a good day.
