### ISSUE TITLE
Keep file's original layout when Marshaling

### ISSUE THREAD

**Issue by livingsilver94** [go-yaml/yaml#445]
I am updating single entries in YAML files by unmarshaling them to `map[string]interface{}`, editing the entries I want to change and then marshal the object again. By doing this though, I get files formatted the `go-yaml`'s way, it doesn't keep the original layout (indendation, mostly). Is there any way to keep files as they are?

**Comment by niemeyer** [comment]
With a map, there's no way at all to do this since there isn't enough information about the source file.

Starting with v3 you can keep more of the formatting untouched using Node, but it will still format its own way. Please see [the v3 announcement](https://blog.ubuntu.com/2019/04/05/api-v3-of-the-yaml-package-for-go-is-available) for details.

**Comment by livingsilver94** [comment]
With Node, how can I keep some fields untouched? Say I have 
```yaml
key1    : value1     # I want to ignore it
key2    : value2
key3    : value3
anythingelse: values # I want to ignore these too
```
I want to be able to marshal key2 and key3, while retaining key1 and anythingelse. key1 is a fixed field, but anythingelse in this case is a _placeholder_ for multiple fields which I don't know a priori, they're not fixed and known. The solution for key1 is easy, I would just use
```go
type MyStruct struct {
    KeyOne   yaml.Node `yaml:"key1"`
    KeyTwo   string    `yaml:"key2"`
    KeyThree string    `yaml:"key3"`
}
```
But for fields following key3 I don't have a tag to associate to, because they are many. Is there a solution for this? Well, except Implementing `Unmarshaler` for my specific case.

**Comment by mullerch** [comment]
This feature would be very interesting to edit a yaml file changing as few lines as possible.

I don't understand why this issue is closed, does something provide this feature ? Is there a reason not to implement it / refuse it ?

Now with v3 it should be not too tricky to implement using the Line and Column property to respect the original layout. 

Correct positioning of the LineComment would still be problematic as their position is not stored. Also an additional node or comment would need correction of the Column position of the following nodes to keep it consistent.

This could be an option for the marshaller, using a new function to avoid breaking change.

**Comment by niemeyer** [comment]
We can and will likely improve how much of the original layout is preserved over time, and v3 goes a long way into that direction already. That said, it's explicitly not a goal of the project to keep the exact same text as the origin as described in this issue. We don't even have enough information in the decoded tree to do that.
