### ISSUE TITLE
Go module

### ISSUE THREAD

**Issue by myles-mcdonnell** [go-yaml/yaml#446]
I'm having trouble referencing this package as a go mod, any advice? currently my code base references version 2 via gopkg.in

**Comment by efimovalex** [comment]
Same here, getting the following error: 
`github.com/go-yaml/yaml@v0.0.0-20181115110504-51d6538a90f8: parsing go.mod: unexpected module path "gopkg.in/yaml.v2"`

**Comment by Existed** [comment]
I get the same error:
```Shell
$ go mod vendor
go: finding github.com/go-yaml/yaml 55513cacd4ae8b250e3a9084ab9d8c407b1ed618
go: github.com/go-yaml/yaml@v0.0.0-20190502103701-55513cacd4ae: parsing go.mod: unexpected module path "gopkg.in/yaml.v3"
go: error loading module requirements
```

The following is successful in `go.mod` : 
```Shell
reuqire (
    gopkg.in/yaml.v3 v3.0.0-20190502103701-55513cacd4a
)
```
```Shell
$ go mod vendor
go: finding gopkg.in/yaml.v3 v0.0.0-20190502103701-55513cacd4ae
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
```

**Comment by niemeyer** [comment]
As the error indicates, the module path to be used in the code is indeed gopkg.in/yaml.v3.

**Comment by thrawn01** [comment]
When converting from `godep` to modules support, `go mod init` adds `github.com/go-yaml/yaml@v0.0.0-20181115110504-51d6538a90f8` to `go.mod`.  This addition causes the error since the `go.mod` for this project declares this to be the repo for `module "gopkg.in/yaml.v2"`

I had to remove the offending `github.com/go-yaml/yaml` path and add the correct path `gopkg.in/yaml.v2 v2.2.2`

**Comment by mcandre** [comment]
The current YAML package structure breaks downstream components in recent Go versions. For example, `go get github.com/tsg/gotpl` no longer works.

Can we update YAML to match Go expectations for more straightforward integration? Could be as simple as changing the dot to a slash in the import path.

Update:

I have reason to suspect my local proxy configuration causing the issue on my machine. I'll get back to you.

**Comment by willemavjc** [comment]
> The current YAML package structure breaks downstream components in recent Go versions. For example, `go get github.com/tsg/gotpl` no longer works.

I do agree.

With the Go Module behavior that started from 1.11 and which should be the default way with 1.14 (coming soon), I would say that relying on `gopkg.in` instead of `github.com` implies that things are getting more and more complicated for devs.

(Personal point of view.) GitHub's YAML's community is not really at fault though as this comes from Golang whose moves are quite ...hazardous somehow (i.e. GOMODULE111 behavior depending of Go version).

`go.mod` can be modified in such way it does not imply a breaking change for dependencies:
```
module github.com/go-yaml/yaml/v3

go 1.13

require gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
```

Note the `/v3` at the end to deal with the `go get [...] invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3` error.

> This comes from the way module versioning was designed in Golang.
> See documentation [here](https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning)

From there, with a proper release tag (say `v3.0.0`) which also lacks on the current YAML repository actually, everything works like a charm.

Example done on a docker alpine with YAML forked:
```
docker container run --rm -it golang:1.13.6-alpine sh
apk add git
mkdir /app
cd /app
go mod init github.com/user/repo
go get github.com/user/yaml/v3@v3.0.0
```

I do not know if this would affect gopkg.in behavior. I tend to not use it like a large part of Go community in fact because many prefer to source on ...well, the source repository with no middle "agents".
