### ISSUE TITLE
"duplicated key" error when overriding embedded struct field

### ISSUE THREAD

**Issue by osela** [go-yaml/yaml#467]
consider the following example where struct `test` both embeds a type with field `a` and owns a field `a`:
```
type embedded struct {
	A string `yaml:"a"`
}

var test struct{
	embedded `yaml:",inline"`
	A string `yaml:"a"`
}

txt := `a: test`

if err := yaml.Unmarshal([]byte(txt), &test); err != nil {
	panic(err)
}
fmt.Printf("%+v", test)
```
this code panics with `duplicated key` error using both v2 and v3.
When using the `encoding/json` package the same example works and the value is decoded into the container struct field, which takes precedence over the embedded struct field.

This is extremely painful when trying to use v3 to extract the location (line and column) of each object in an object hierarchy. This is the code I would expect to write:
```
type SourceRef struct {
	Line int
	Column int
}

type File struct {
	Name string `yaml:"name"`
	SourceRef *SourceRef `yaml:"-"`
}

type Dir struct {
	Name string `yaml:"name"`
	Files []*File `yaml:"files"`
	// some more fields
	SourceRef *SourceRef `yaml:"-"`
}

txt := `
name: my-dir
files:
- name: file1
- name: file2
`

var node yaml.Node
if err := yaml.Unmarshal([]byte(txt), &node); err != nil {
	panic(err)
}

var apiDirNode struct{
	*Dir `yaml:",inline"`
	Files []yaml.Node `yaml:"files"`
}

if err := node.Decode(&apiDirNode); err != nil {
	panic(err)
}

apiDir := apiDirNode.Dir
apiDir.SourceRef = &SourceRef{
	Line: node.Line,
	Column: node.Column,
}

for _, fileNode := range apiDirNode.Files {
	var file *File
	if err := fileNode.Decode(&file); err != nil {
		panic(err)
	}
	file.SourceRef = &SourceRef{
		Line: fileNode.Line,
		Column: fileNode.Column,
	}
	apiDir.Files = append(apiDir.Files, file)
}
```
but instead I'm forced to copy all `Dir` fields to `apiDirNode` and then extract them again when constructing a `Dir`.

**Comment by niemeyer** [comment]
The code prevents ambiguities to avoid confusing and error prone logic from being used.

This is of course subjective, but the example provided makes me feel like this is a correct choice for this case as well. Having DirNode.Files overriding DirNode.Dir.Files when everything else in DirNode.Dir is inlined as-is indeed feels confusing and error prone.

If you really want to force this, you can always provide a custom yaml.Marshaler interface and go wild, but the default behavior of preventing such unclear logic still feels sound. Again, it's subjective, and I apologize that this might make your code slightly longer.

**Comment by tommie** [comment]
This is a closed issue, but since Go itself does resolution this way (and `encoding/json` inherited that after Go 1.1), this treatment in YAML was unexpected to me.

Is there any chance we could have this enabled with an option, like `KnownFields`?

My use-case is that I have an underlying type to unmarshal, but want to override some specific fields. I'd like to avoid having to need code to copy from the "YAML version" to the "main version" of the structs, as this is prone to forgetting to update the code as new fields are added.

```go
type ComplicatedStruct struct {  // Generated by the Protobuf compiler.
}

type A struct {  // Generated by the Protobuf compiler.
  I int64
  C ComplicatedStruct
}

type yamlA struct {
  A  `yaml:",inline"`

  C string   // Text format to be parsed by custom code.
}
```

The structs are generated by the Protobuf compiler, which means I don't have an easy way to inject `yaml:"-"`.

The current answer to this issue is that I'd write a custom `yamlA.Unmarshaler`, but AFAICT, the YAML library doesn't make it very easy to deal with single-field exceptions, so it's roughly the same result as having to copy between structs. (Please correct me if I'm wrong.)
