### ISSUE TITLE
V3: multiple merge throw error

### ISSUE THREAD

**Issue by cravler** [go-yaml/yaml#478]
https://play.golang.org/p/MH_RpyD1gpW

``` golang
package main

import (
    "fmt"
    "log"
    "gopkg.in/yaml.v3"
)

var data = `
tmp: &TMP
    tmp: 123
foo: &FOO
    x: 1
bar: &BAR 3
baz:
    z: *BAR
    << : *TMP
    y: 2
    << : *FOO
`

func main() {
    unmarshalled := &yaml.Node{}

    err := yaml.Unmarshal([]byte(data), unmarshalled)
    if err != nil {
        log.Fatalf("error: %v", err)
    }

    var expanded interface{}
    err = unmarshalled.Content[0].Content[7].Decode(&expanded)
    if err != nil {
        log.Fatalf("error: %v", err)
    }

    d, err := yaml.Marshal(expanded)
    if err != nil {
        log.Fatalf("error: %v", err)
    }
    fmt.Printf("%s\n", string(d))
}
```

Output error:
```
2019/06/27 09:00:00 error: yaml: unmarshal errors:
  line 11: mapping key "<<" already defined at line 9
```

**Comment by niemeyer** [comment]
The error is in fact correct. There's no special support for the "<<" key in the yaml specification. It's a "language independent type" recommended in a [working draft](https://yaml.org/type/merge.html). As such, the same rules that apply to normal keys in yaml apply here as well, including the fact they shouldn't be duplicated.

Also, note that the working draft never suggests such a construct, and instead explicitly supports the merging of multiple maps via a list value for the special key.

So it looks like the current behavior is correct. Please let me know otherwise.

**Comment by ArcticSnowman** [comment]
@niemeyer -  Seems that the  V2 of this package used to allow this but V3 took it away.  

https://github.com/helm/helm - Uses `sigs.k8s.io/yaml v1.2.0` which in turn references `V2` accept this construct while https://github.com/hairyhenderson/gomplate uses `V3` does not.

If/When Helm update it could break things, so should at the very least be highlighted as a break between V2 and V3
