### ISSUE TITLE
Provide an option to ignore comments completely. 

### ISSUE THREAD

**Issue by mmilley** [go-yaml/yaml#519]
The nature of a comment in any data file is that it is there for human readability and should be *ignored* by the parser. 

I'm not sure why this isn't default behavior; a developer shouldn't have to run every field through a regex to strip out comments after the fact...

**Comment by mmilley** [comment]
Example:

name: |
test 
#my long comment
thing

current result: 
myObj.Name=="test\n#my long comment\nthing" 

expected result:
myObj.Name=="test\nthing"

**Comment by niemeyer** [comment]
The context missing from your reasoning is that in modern times we frequently have tools operating on text which is oriented for human consumption. Comments are there for the humans, and should remain there for the humans after processing. Whether you agree with that or not, this was by far the most requested feature for many years, so some people agree.

With that said, having an option to ignore them sounds fine.

**Comment by farrellit** [comment]
> The nature of a comment in any data file is that it is there for human readability and should be ignored by the parser.

Octothorpe is not a universal comment.  It is in some formats, it isn't in others.  And comments in payloads, even if they are intended for people, shouldn't just inherently be stripped.  

If the comment was a _YaML_ comment it would be easy to agree, because it would be out of spec not to ignore yaml comments.  But it's not a yaml comment.  It's a valid part of the multiline string data : https://stackoverflow.com/questions/20890445/yaml-comments-in-multi-line-strings

You're asking the YaML parser to remove lines from the `name` scalar of the yaml data?  Those aren't yaml comments.  I think it's pretty insane to have code in the yaml parser to ignore any lines matching `^\s*#`, even as an option.  Filtering the accurately formated data inside a yaml object should not be the responsibility of yaml.  It should be the responsibility of the code that handles the data once unmarshalled.

**Comment by mikefarah** [comment]
Yeah this would be nice - mainly as a stop gap for issues:

- https://github.com/go-yaml/yaml/issues/459 (when comment positions break other yaml tools, despite being valid yaml)
- https://github.com/go-yaml/yaml/issues/538 (some comments cause the parser to break)

**Comment by niemeyer** [comment]
Flagging off every corner of the code to avoid handling comments is more complex than not doing it, which seems to be the opposite of the request presented here (doing something simpler), but it should be trivial to cook a function to just zero out comments recursively in a node structure if you really don't care about them. Also, this will only play a role if people are decoding and re-encoding a Node structure exactly as-is, which is generally an attempt to preserve as much as possible.

For those reasons, I'll try to move forward without a flag for the time being. It's always easier to add those things later than to remove them.
