### ISSUE TITLE
missing colon ':' leads to wrong line number of error

### ISSUE THREAD

**Issue by thetillhoff** [go-yaml/yaml#542]
This seems to occur in every yaml file where an expected colon is missing.
The Parser states it could not find an expected ':' on the NEXT line, which is why I assume the parser breaks multiple values in a single line into multiple lines with a single value each.
An example would be:
```
---
somevar:
  anothervar 1
  bnothervar: 2
```
Which would result in an error: "yaml: line 4: could not find expected ':'" instead of pointing to line 3.

As already stated, I guess this is related to the following behaviour:
```
---
somevar:
  anothervar 1:
  bnothervar: 2
```
As the "anothervar 1:"-line is broken into actual two lines within the parser.

**Comment by niemeyer** [comment]
In some of those cases it will complain about the follow up line because the lack of syntax will mean the previous token is interpreted as spanning multiple lines. That said, it's not entirely clear that this is what's going on in this particular case, and I know we already have some logic for handling errors from the scanner. Let me dig into this a bit.

**Comment by niemeyer** [comment]
I've changed the behavior with b1b19b4 so that it looks first at the context mark instead of the problem mark. This seems more appropriate since the problem mark is the one where the current parser sits wherever that ends up being , instead of the one which was explicitly provided at error report time. Let's see how well that works. It certainly fixes this problem specifically.

Let me know if you see any issues related to this please.

**Comment by thetillhoff** [comment]
Thank you very much for digging into this and fixing it!
