### ISSUE TITLE
Curious list formatting when using indent of 3

### ISSUE THREAD

**Issue by manute** [go-yaml/yaml#559]
Hi there! ,

I was just testing the indentation for a custom encoder and I saw different results for lists.

This is an example test:

```golang
import (
	"bytes"
	"fmt"
	"testing"

	"gopkg.in/yaml.v3"
)

type Element struct {
	One string `yaml:"one"`
	Two string `yaml:"two"`
}

type Elements struct {
	S []Element `yaml:"elements"`
}

type Root struct {
	Elements Elements `yaml:"root"`
}

func TestSliceIndent(t *testing.T) {
	root := Root{Elements{[]Element{{"one", "two"}}}}

	out, err := encode(root, 2)
	if err != nil {
		t.Error(err)
	}
	fmt.Printf("Encode 2 spaces: \n%s\n", string(out))

	out, err = encode(root, 4)
	if err != nil {
		t.Error(err)
	}
	fmt.Printf("Encode 4 spaces: \n%s\n", string(out))

	out, err = encode(root, 3)
	if err != nil {
		t.Error(err)
	}
	fmt.Printf("Encode 3 spaces: \n%s\n", string(out))

}

func encode(r Root, spaces int) ([]byte, error) {
	var b bytes.Buffer
	e := yaml.NewEncoder(&b)
	e.SetIndent(spaces)

	if err := e.Encode(&r); err != nil {
		return nil, err
	}
	return b.Bytes(), nil

}

```text

Encode 2 spaces:
root:
  elements:
  - one: one
    two: two

Encode 4 spaces:
root:
    elements:
      - one: one
        two: two

Encode 3 spaces:
root:
   elements:
    -
     one: one
     two: two

```

*All the results are valid yaml*, but I think the lists should have the format like the 4 spaces result. Also the 3 spaces indentation seems strange, although I don't know if anyone is using an odd number for indention 😄 .

**Comment by niemeyer** [comment]
You seem to have edited the report since creation. I believe you likely had out of date code running locally, since the current report feels more reasonable.

The three spaces look curious, still. Maybe it needs to be special cases so it looks closer to the the 2 spaces case. The issue isn't it being odd or even, but making indentation look proper when it's too short. The 2 spaces case is already handled in a custom way so it looks nice, for instance, as shown in your output above.

**Comment by manute** [comment]
Well I just edited because the github format output text was showing different results :) .

Regarding the issue, I think I created it with the wrong title, sorry. What I was trying to explain is that  the lists don't indent accordingly with the spaces passed to the `encoder.SetIndent`.  

Don't you think it would make sense for example if the list always behave in the same way?

**Comment by niemeyer** [comment]
> Don't you think it would make sense for example if the list always behave in the same way?

Can you clarify that?  I see an obvious bug in the way the indent of 3 is working. What else do you see incorrect or inconsistent there which you'd like to fix?

**Comment by manute** [comment]
Sure, when 2 spaces , the list has not got any indentation. When 4 spaces, the list has 2 spaces of indentation. And when 3 I don't know :) 

My point is that I think it would make more sense to have always for list 2 spaces of indentation or  respect the spaces of indentation passed for the encoder.

**Comment by niemeyer** [comment]
Okay, so it's not about consistency, nor about being the same as the 4 space result as requested on the original post either. You want all of them to look different from what they are today.

Fair enough. We're trying a slightly different style in v3. We can easily go back if it turns out this is not a good idea in practice.

The 3 spaces indent definitely needs fixing no matter what.

**Comment by manute** [comment]
I think it's all about consistency, also I think the best approach would be that the list should respect the indent spaces passed for the `encoder.SetIndent`.  Because It feels awkward that the lists don't format the same way as the others.

**Comment by niemeyer** [comment]
The list has a leading character. The spacing is discounting that so that this is possible at all:
```
foo:
- a
- b
```
That's been like that since go-yaml was created, and was inherited from libyaml.

In v3 we simply took that approach and expanded to the other cases, making it consistent. So this is two spaces, and four spaces simply adds two spaces to it, literally. And consistently. :)

Now, you want something else, which I understand. I can't decide whether to change everything or not based on this conversation, unfortunately. I'll need to look through more examples before we tune that again.

_(edit: fix typo)_

**Comment by manute** [comment]
Ok I understand it. Thanks for your time.

**Comment by niemeyer** [comment]
Okay, I've seen a few more files with awkward formatting and I'm convinced you're right.

I'll change v3 soon to avoid that wart. Thanks for the feedback.

**Comment by niemeyer** [comment]
This was sorted in ae27a74. Please drop me a note if you see any other issues.

**Comment by manute** [comment]
Thanks!

**Comment by niemeyer** [comment]
I've touched on the indentation logic again in a5ece68 to make it more regular, as there were still awkward cases. What should happen now is that the first level under a block sequence should be indented right after the indicator, but everything else should respect the selected levels.

The result should be something like this, assuming 4 spaces:
```
one:
    - two: 2
      three:
        - 3
    - four:
        - 4
```

**Comment by manute** [comment]
yeah that should be fine . Thanks for your work
