### ISSUE TITLE
Special character swap error

### ISSUE THREAD

**Issue by qimingxingyuliyang** [go-yaml/yaml#565]
`
package main

import (
	"fmt"
	"io/ioutil"
	"log"

	"gopkg.in/yaml.v2"
)

//Nginx nginx  配置
type Nginx struct {
	Port    int    `yaml:"Port"`
	LogPath string `yaml:"LogPath"`
	Path    string `yaml:"Path"`
}

//Config   系统配置配置
type Config struct {
	Name      string  `yaml:"SiteName"`
	Addr      string  `yaml:"SiteAddr"`
	HTTPS     bool    `yaml:"Https"`
	SiteNginx []Nginx `yaml:"Nginx"`
}

func main() {
	var setting Config
	config, err := ioutil.ReadFile("./test.yaml")
	if err != nil {
		fmt.Print(err)
	}
	yaml.Unmarshal(config, &setting)
	data, err := yaml.Marshal(&setting)
	if err != nil {
		log.Fatalf("error: %v", err)
	}
	fmt.Printf("--- m dump:\n%s\n\n", string(data))
	ioutil.WriteFile("./out.yaml", data, 0777)
}
`

**Raw data：**

`
SiteName: seeta
SiteAddr: BeiJing
Https: true
Nginx:
    - Port: 443
      LogPath: >
          "/var/log//nginx/nginx.log"
      Path: "/opt/nginx/"
`

**Output after execution**

`
SiteName: seeta
SiteAddr: BeiJing
Https: true
Nginx:
- Port: 443
  LogPath: |
    "/var/log//nginx/nginx.log"
  Path: /opt/nginx/
`
the right arrow becomes vertical   "> "  ==>   "|"

=============================================
region: !region_component   ======>  region: ""

**Comment by niemeyer** [comment]
Yes, it's not a "character swap". Your data is exactly the same. What you are seeing is that the formatting of the output is not the same as the input, and that's impossible in this case since there's no information in your structure that would allow preserving the output. If you want to make the output closer to the input, your best bet is looking into [yaml.Node in v3](https://gokpg.in/yaml.v3#Node), but even that will not preserve 100% of the formatting in the input.
