### ISSUE TITLE
How to make inner sequence as flow style

### ISSUE THREAD

**Issue by goomadao** [go-yaml/yaml#566]
Such struct:
```
type Tmp struct {
	nodes []Node `yaml:"nodes,flow"`
}
```
will create such yaml file:
```
nodes: [{type: ss1, cipher: aes-256-cfb}, {type: ss2, cipher: aes-256-cfb}, {type: ss3, cipher: aes-256-cfb}, {type: ss4, cipher: aes-256-cfb}, {type: ss5, cipher: aes-256-cfb}]
```
Is there any way to create yaml file like this:
```
nodes:
  - {type: ss1, cipher: aes-256-cfb}
  - {type: ss2, cipher: aes-256-cfb}
  - {type: ss3, cipher: aes-256-cfb}
  - {type: ss4, cipher: aes-256-cfb}
  - {type: ss5, cipher: aes-256-cfb}
```
?

**Comment by niemeyer** [comment]
Yes, just tune the Style of the nodes themselves in this case:

- https://gopkg.in/yaml.v3#Node
- https://gopkg.in/yaml.v3#Style

**Comment by xoac** [comment]
I would appreciate example how to properly use it. As far as I understand - `Node` need to by of type `yaml.Node` for `my.Node` I need to create custom function like this:

```
func (d *Node) MarshalYAML() (interface{}, error) {
	node := &yaml.Node{}
	err := node.Encode(d)
	node.Style = yaml.FlowStyle
        return node, err
}
```
(This does not work in my case - I got panic due to stack overflow)

It would be also nice to see examples of styles in documentation.
