### ISSUE TITLE
Comment moves past '-' character in round-trip

### ISSUE THREAD

**Issue by bboreham** [go-yaml/yaml#628]
I noticed this because it created a diff in the file even though it's semantically the same.

```
package main

import (
        "fmt"

        "gopkg.in/yaml.v3"
)

var data = `
b:
# a comment
- c: 2
`

func main() {
        t := yaml.Node{}
        _ = yaml.Unmarshal([]byte(data), &t)
        d, _ := yaml.Marshal(&t)
        fmt.Printf("%s\n", string(d))
}
```
```
b:
    - # a comment
      c: 2
```
https://play.golang.org/p/9zKd5-A7eKJ

**Comment by niemeyer** [comment]
Managing that sort of structure was greatly improved a few days ago with a5ece68, but I've missed this case not realizing that the indentless sequence goes through a different code path.

I've extended that fix for indentless sequences with  c8ae1108, so that this should now roundtrip correctly as well:
```
foo:
# Head comment of following map
- # Head comment of bar
  bar: # Line comment of bar
    baz # Line comment of baz
```
Thanks for the report.
