### ISSUE TITLE
v3: Value of `null` gets marshalled to "null"

### ISSUE THREAD

**Issue by gotjosh** [go-yaml/yaml#674]
Hey everyone, thank you very much for all your hard work!

There's some potential odd behaviour that I can't get my head around, for a struct that looks like:

```
type RuleGroup struct {
	Rules    []RuleNode     `yaml:"rules"`
}

type RuleNode struct {
	Alert       yaml.Node         `yaml:"alert,omitempty"`
	Expr        yaml.Node         `yaml:"expr"`
}
```

When I try to marshal something like:

```
rules:
- alert: ANullAlert
  expr: null
```

The value of `expr` is `"null"` instead of `""`, the keyword `Null` procudes the same result but using something like `~` does indeed works as expected and the value is `""`. Am I missing something or is this unexpected behaviour?

For context, https://github.com/cortexproject/cortex/issues/3413 here's a concrete example / implementation.

**Comment by niemeyer** [comment]
This is not normal behavior, and we have plenty of tests with nulls marshaling them properly. Are you marshaling a string with the "null" value instead of an actual nil value?  That's what it looks like since you're pointing out that null produces "". That would explain the problem.

Otherwise, if you can provide an example at play.golang.org I'm happy to look at it.
