### ISSUE TITLE
v3: YAML (un?)marshalling adds strange numeric characters

### ISSUE THREAD

**Issue by zx8** [go-yaml/yaml#701]
Using https://github.com/go-yaml/yaml/commits/496545a6307

---

### Repro

```go
package main

import (
	"fmt"

	"gopkg.in/yaml.v3"
)

func main() {
	data := []byte(`
foo:
  - |

    bar
    `)
	var result map[string]interface{}
	if err := yaml.Unmarshal(data, &result); err != nil {
		panic(err)
	}
	b, err := yaml.Marshal(result)
	if err != nil {
		panic(err)
	}
	fmt.Print(string(b))
}
```

### Actual

```yaml
foo:
    - |4
      bar
```

### Expected

```yaml
foo:
    - |

      bar
```

**Comment by johnweldon** [comment]
I believe the number `4` in this case is an indentation hint; the number of spaces to prefix each line with.  For me the problem is that `go-yaml` itself doesn't seem to know how to *un*-marshal YAML that has this hint.

(See [this](https://yaml-multiline.info/), and check the 'include indentation indicator' checkbox )

**Comment by zhranklin** [comment]
Is there any progress of this problem?

**Comment by zx8** [comment]
Closing as this is 3 years old without any movement.
