### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by msugakov** [go-yaml/yaml#776]
My apologies for raising a question like this. I see that except of CI pipeline update, last merged requests are from more than a year ago.
https://github.com/go-yaml/yaml/pulls?q=is%3Apr+sort%3Acreated-desc+is%3Amerged
There are some (seemingly) trivial to merge requests that could improve our life a bit ([1](https://github.com/go-yaml/yaml/pull/539), [2](https://github.com/go-yaml/yaml/pull/488)) but we're not even getting any responses there.
It would be good to know what's the situation with this project, and, if there are difficulties, how could users community potentially help?

**Comment by niemeyer** [comment]
It is maintained, and neither responses here or commits are older than a year. But I maintain this project whenever I have some space from other work, which hasn't happened recently, and I'm not even sorry for that because to be honest there are many interesting things going on that require my attention. Still, I do care about go-yaml, and it's a dependency on many of our projects, so it's not going away, and it's not going to be unmaintained any time soon. But this is not your typical project with lots of active maintainers, and that is indeed unfortunate, but reality.
