### ISSUE TITLE
failed to parse yaml, got error `did not find expected key`

### ISSUE THREAD

**Issue by asdfsx** [go-yaml/yaml#780]
Unmarshal a yaml file, which contain following config
```
servings:
  hosts:
    - :
```
And got following error
```
          <*errors.errorString | 0xc0002ca710>: {
              s: "yaml: line 83: did not find expected key",
          }
          yaml: line 83: did not find expected key
```
Is there any way to parse config like this?

I create a playground for testing [playground](https://play.golang.org/p/W5Z_GxKnlqJ)

**Comment by perlpunk** [comment]
Just a note from the perspective of the YAML spec:
While a mapping entry with both key and value being empty is valid, it is not recommended and at least the key should be explicitly quoted, e.g. `'': `. Also because several libraries can not parse it.
The YAML team is considering removing the possibility for completely empty mapping keys for the next YAML version.

**Comment by asdfsx** [comment]
So the best way to solve the problem is to modify the config file, or the templates which generate the config
Thx

**Comment by asdfsx** [comment]
@perlpunk 
In my config, it's not a map with empty key, but it's a string only contain `:`

**Comment by perlpunk** [comment]
A string only containing `:` cannot be written as a plain scalar in YAML. How should the YAML processor know that you mean just a string and not the special key/value separator?
Use single quotes. `':'`

**Comment by asdfsx** [comment]
I have modified origin yaml template to solve the problem
Thx a lot @perlpunk
