### ISSUE TITLE
still use pkg.in as proxy in the future?

### ISSUE THREAD

**Issue by coticom** [go-yaml/yaml#925]
i think github.com more stable than pkg.in, use go get https://github.com/go-yaml/yaml/v3 more better.

**Comment by leonardocustodio** [comment]
We are having a lot of issues for the past month with this lib because of gopkg.in
The service is very unreliable and is always down...

**Comment by niemeyer** [comment]
Uptime of gopkg.in is at 98.75%, which although not good is far from "always down", and worse than the past 10 years we've been keeping this service alive, due to recent data center connectivity issues. Of course, by definition using just github.com will always be more stable than gopkg.in, because the latter will present the sum of both downtimes since it depends on GitHub itself.

Sorry for your trouble.

**Comment by niemeyer** [comment]
You can find that data in status.canonical.com, btw.

**Comment by leonardocustodio** [comment]
Ok sorry I think I over reacted with the `always down` but for the past 2 months we really had a hard time with building some applications that depends on this service. And that was over 30 times that's why I over reacted. But you are right I will move to use GH, thank you for the fast reply

**Comment by niemeyer** [comment]
I can relate, as stuff breaks on our end as well when that happens. I need to look into it to make sure these problems stop, otherwise we'll need to move the service again.
